#!/usr/bin/env bash
# Stamps a new build version into index.html and login.html so browsers and CDNs fetch fresh
# copies of every JS module and stylesheet after a deploy, instead of serving stale ones.
#
# There's no bundler, so the pages load ES modules by plain URL — and a cached
# js/project-form.js can outlive a deploy even when index.html itself is fresh. This rewrites
# the block between <!-- build:start --> and <!-- build:end --> with:
#   - <meta name="build">, shown in the sidebar footer so you can see which build is live
#   - an import map sending every js/*.js module to the same file + ?v=<build>
# and appends ?v=<build> to the entry script (js/app.js) and the stylesheet links.
#
# Run it from the repo root before committing a change that should go live:
#   scripts/stamp-build.sh
set -euo pipefail
cd "$(dirname "$0")/.."

BUILD="$(date -u +%Y%m%d.%H%M)-$(git rev-parse --short HEAD 2>/dev/null || echo local)"

imports=""
for f in js/*.js; do
  imports+="${imports:+,
}    \"./$f\": \"./$f?v=$BUILD\""
done

block="<!-- build:start (generated by scripts/stamp-build.sh — do not edit by hand) -->
<meta name=\"build\" content=\"$BUILD\">
<script type=\"importmap\">
{
  \"imports\": {
$imports
  }
}
</script>
<!-- build:end -->"

for page in index.html login.html; do
  BLOCK="$block" python3 - "$page" "$BUILD" <<'PY'
import os, re, sys
path, build = sys.argv[1], sys.argv[2]
html = open(path, encoding='utf-8').read()
block = os.environ['BLOCK']
if '<!-- build:start' in html:
    html = re.sub(r'<!-- build:start.*?<!-- build:end -->', lambda m: block, html, flags=re.S)
else:
    html = html.replace('</head>', block + '\n</head>', 1)
# version the entry script and stylesheets
html = re.sub(r'(src="\./js/app\.js)(\?v=[^"]*)?"', rf'\1?v={build}"', html)
html = re.sub(r'(href="\./css/[\w.-]+\.css)(\?v=[^"]*)?"', rf'\1?v={build}"', html)
open(path, 'w', encoding='utf-8').write(html)
PY
done

echo "Stamped build $BUILD into index.html and login.html"
